export { Navbar } from './navbar';
export { Hero } from './hero';
export { PainPoints } from './pain-points';
export { HowItWorks } from './how-it-works';
export { Industries } from './industries';
export { Features } from './features';
export { Pricing } from './pricing';
export { Testimonials } from './testimonials';
export { FAQ } from './faq';
export { ApplyForm } from './apply-form';
export { Footer } from './footer';
export { LanguageProvider, useLanguage } from './language-context';
